// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6slaeMVCy1RbhPmR_EKKP62RXVAat090',
    appId: '1:1054139527182:web:bee42805b6d5b21c8b0c5f',
    messagingSenderId: '1054139527182',
    projectId: 'cybershop-71228',
    authDomain: 'cybershop-71228.firebaseapp.com',
    storageBucket: 'cybershop-71228.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdF0zV46VhRPHzdLWFT7XjL8Qy_2Oyp6U',
    appId: '1:1054139527182:android:d6713e75d1aa0ec98b0c5f',
    messagingSenderId: '1054139527182',
    projectId: 'cybershop-71228',
    storageBucket: 'cybershop-71228.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6slaeMVCy1RbhPmR_EKKP62RXVAat090',
    appId: '1:1054139527182:web:6c979771c3f576548b0c5f',
    messagingSenderId: '1054139527182',
    projectId: 'cybershop-71228',
    authDomain: 'cybershop-71228.firebaseapp.com',
    storageBucket: 'cybershop-71228.appspot.com',
  );

}